title: NBBC Media Docs
description: Reference material supporting the roles within NBBC's Media Team
theme: just-the-docs

url: https://nbbcmedia.github.io/nbbcmedia
permalink: pretty

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

callouts:
  warning:
    title: Warning
    color: red
  new:
    color: green
