title: NBBC Media Docs
description: Reference material supporting the roles within NBBC's Media Team
theme: just-the-docs
logo: "/asset/NBBC-Docs-Logo2.png"

url: https://nbbcmedia.github.io/nbbcmedia
permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
